export type MeetingStatus = "scheduled" | "done" | "pipeline";

export interface ClientDetail {
  id: string;
  meetingId: string;
  month: string;
  year: number;
  clientName: string;
  geo: string;
  salesRep: string;
  accountManager: string;
  meetingDate: string;
  meetingTime: string;
  meetingStatus: MeetingStatus;
  meetingLink: string;
  companyName: string;
  contactName: string;
  contactTitle: string;
  contactEmail: string;
  contactNumber: string;
  remarks: string;
  additionalInfo: string;
  meetingSummary: string;
}

export const clientDetails: Record<string, ClientDetail[]> = {
  p1: [
    { id: "d1", meetingId: "MTG-1001", month: "April", year: 2026, clientName: "Thyleads", geo: "APAC", salesRep: "Rahul Verma", accountManager: "Akash S", meetingDate: "2026-04-02", meetingTime: "10:00 AM", meetingStatus: "done", meetingLink: "https://meet.google.com/bjgwdi8w", companyName: "Thyleads", contactName: "Amit Shah", contactTitle: "CEO", contactEmail: "amit.s@thyleads.com", contactNumber: "+91-80-555-0101", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d2", meetingId: "MTG-1002", month: "April", year: 2026, clientName: "Thyleads", geo: "US-East", salesRep: "Rahul Verma", accountManager: "Rohit M", meetingDate: "2026-04-08", meetingTime: "02:30 PM", meetingStatus: "scheduled", meetingLink: "https://meet.google.com/zda6icf8", companyName: "Thyleads", contactName: "Priya Menon", contactTitle: "VP Sales", contactEmail: "priya.m@thyleads.com", contactNumber: "+1-212-555-0102", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d3", meetingId: "MTG-1003", month: "March", year: 2026, clientName: "Thyleads", geo: "APAC", salesRep: "Rahul Verma", accountManager: "Prateek G", meetingDate: "2026-03-15", meetingTime: "11:00 AM", meetingStatus: "done", meetingLink: "https://meet.google.com/juunnuav", companyName: "Thyleads", contactName: "Sanjay Kapoor", contactTitle: "CTO", contactEmail: "sanjay.k@thyleads.com", contactNumber: "+91-80-555-0103", remarks: "", additionalInfo: "", meetingSummary: "" },
  ],
  p2: [
    {"id":"d2001","meetingId":"MTG-2001","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Sandeep","meetingDate":"2026-01-08","meetingTime":"03:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Eagle Footwear","contactName":"Karan Bhagat","contactTitle":"Director","contactEmail":"krbhagat11694@gmail.com","contactNumber":"9879696972","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2002","meetingId":"MTG-2002","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-06","meetingTime":"11:00 AM","meetingStatus":"done","meetingLink":"","companyName":"Project Shades","contactName":"Raj Azad","contactTitle":"Founder","contactEmail":"raj@projectshades.com","contactNumber":"9075007864","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2003","meetingId":"MTG-2003","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-07","meetingTime":"03:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Aisha Rao","contactName":"Mourya Pulugu","contactTitle":"Growth Marketing Manager","contactEmail":"mourya@aisharao.com","contactNumber":"9390746799","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2004","meetingId":"MTG-2004","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-07","meetingTime":"12:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Banter Kitchen","contactName":"Vikas Prakash","contactTitle":"Founder’s Office","contactEmail":"hello@banterkitchen.com","contactNumber":"9849947260","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2005","meetingId":"MTG-2005","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-06","meetingTime":"02:00 PM","meetingStatus":"done","meetingLink":"","companyName":"VYRAL24","contactName":"Vishal Dhankhar","contactTitle":"Co-Founder","contactEmail":"vishal@vyral24.com","contactNumber":"9306279640","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2006","meetingId":"MTG-2006","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-06","meetingTime":"03:00 PM","meetingStatus":"done","meetingLink":"","companyName":"HealthKart","contactName":"Nishank Agarwal","contactTitle":"Product Lead","contactEmail":"nishank.agarwal@brightlifecare.com","contactNumber":"9958722366","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2007","meetingId":"MTG-2007","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-08","meetingTime":"02:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Rasa Silver Jewels","contactName":"Manan Bohra","contactTitle":"Founder","contactEmail":"mb@rasasilver.com","contactNumber":"7022461367","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2008","meetingId":"MTG-2008","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Sandeep","meetingDate":"2026-01-09","meetingTime":"02:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Wayveda","contactName":"Sunil Munjal","contactTitle":"Director of Digital Marketings","contactEmail":"unilmunjal@digitalchaabi.com","contactNumber":"7015350423","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2009","meetingId":"MTG-2009","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-09","meetingTime":"11:00 AM","meetingStatus":"done","meetingLink":"","companyName":"Mensa Brands","contactName":"Bhooshan Patil","contactTitle":"Brand Head","contactEmail":"bhooshan.patil@mensabrands.com","contactNumber":"","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2010","meetingId":"MTG-2010","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-12","meetingTime":"02:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Chupps","contactName":"Ravi Adhikari","contactTitle":"Marketing & Brand Lead","contactEmail":"ravi@chupps.com","contactNumber":"9820996926","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2011","meetingId":"MTG-2011","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-13","meetingTime":"11:00 AM","meetingStatus":"done","meetingLink":"","companyName":"Rachna Sagar","contactName":"Ashish Gupta","contactTitle":"Business Head","contactEmail":"ashish.gupta@rachnasagar.in","contactNumber":"7042459879","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2012","meetingId":"MTG-2012","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-14","meetingTime":"03:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Duke","contactName":"Gagan Jain","contactTitle":"Brand Head","contactEmail":"gaganjain@duke      india.com","contactNumber":"7443003848","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2013","meetingId":"MTG-2013","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Swetha","meetingDate":"2026-01-08","meetingTime":"04:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Cumin Co","contactName":"Udit Lekhi","contactTitle":"Co-Founder","contactEmail":"udit@cuminco.com","contactNumber":"9971518700","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2014","meetingId":"MTG-2014","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Sandeep","meetingDate":"2026-01-13","meetingTime":"07:00 PM","meetingStatus":"done","meetingLink":"","companyName":"FitFeast","contactName":"Aditya Poddar","contactTitle":"Founder","contactEmail":"aditya@fitfeast.in","contactNumber":"9871285350","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2015","meetingId":"MTG-2015","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-16","meetingTime":"01:30 PM","meetingStatus":"done","meetingLink":"","companyName":"Digitek","contactName":"Saurabh Singh","contactTitle":"Amazon PPC Manager","contactEmail":"saurabh@digitek.net.in","contactNumber":"9654994469","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2016","meetingId":"MTG-2016","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-19","meetingTime":"11:00 AM","meetingStatus":"done","meetingLink":"","companyName":"ARAKU Coffee","contactName":"Kunal Ross","contactTitle":"Deputy General Manager Operations:","contactEmail":"kunal.ross@arakuoriginals.com","contactNumber":"9820114360","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2017","meetingId":"MTG-2017","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-21","meetingTime":"11:30 AM","meetingStatus":"done","meetingLink":"","companyName":"TrueData™ Financial Information","contactName":"Kapil Marwaha","contactTitle":"Founder","contactEmail":"kapil@truedata.in","contactNumber":"9311279054","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2018","meetingId":"MTG-2018","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Sandeep","meetingDate":"2026-01-21","meetingTime":"12:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Jaipur watch","contactName":"Amit","contactTitle":"Sr. manager marketing","contactEmail":"marketing@jaipurwatches.com","contactNumber":"7300074117","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2019","meetingId":"MTG-2019","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Sandeep","meetingDate":"2026-01-21","meetingTime":"03:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Miarucus","contactName":"Mujahid","contactTitle":"Deputy General Manager - Digital","contactEmail":"digital@miarcus.com","contactNumber":"9307536204","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2020","meetingId":"MTG-2020","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-22","meetingTime":"12:00 PM","meetingStatus":"done","meetingLink":"","companyName":"AertekSmart","contactName":"Sumita Das","contactTitle":"Growth Marketing Manager","contactEmail":"sumita.das@aerteksmart.com","contactNumber":"9147729484","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2021","meetingId":"MTG-2021","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-22","meetingTime":"02:00 PM","meetingStatus":"done","meetingLink":"","companyName":"dash and do","contactName":"Rehan Khan","contactTitle":"Manager Ecommerce & CRM","contactEmail":"rehan@dashanddot.com","contactNumber":"8369879288","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2022","meetingId":"MTG-2022","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Sandeep","meetingDate":"2026-01-22","meetingTime":"06:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Pureflow Tape","contactName":"Prikshit","contactTitle":"Co-Founder","contactEmail":"11prikshit21@gmail.com, founders.office@pureflowtape.com","contactNumber":"8284871378","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2023","meetingId":"MTG-2023","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-23","meetingTime":"02:30 PM","meetingStatus":"done","meetingLink":"","companyName":"Old School Rituals","contactName":"Ram Ganesh","contactTitle":"SAP MM Consultant","contactEmail":"ramganesh@oldschoolrituals.in","contactNumber":"7087456456","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2024","meetingId":"MTG-2024","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-27","meetingTime":"12:00 PM","meetingStatus":"done","meetingLink":"","companyName":"My Pahadi Dukan","contactName":"Rohan Sehgal","contactTitle":"Co-Founder","contactEmail":"rohan.sehgal@mypahadidukan.com","contactNumber":"8879454970","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2025","meetingId":"MTG-2025","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Sandeep","meetingDate":"2026-01-27","meetingTime":"02:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Hamptons","contactName":"Harshil Shah","contactTitle":"Co-Founder","contactEmail":"harshil@baaamboos.com","contactNumber":"9374864148","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2026","meetingId":"MTG-2026","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Sandeep","meetingDate":"2026-01-27","meetingTime":"03:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Wear duds","contactName":"Sikandar","contactTitle":"Co-Founder and CEO","contactEmail":"sikandar@wearduds.com","contactNumber":"9871195479","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2027","meetingId":"MTG-2027","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Sandeep","meetingDate":"2026-01-28","meetingTime":"02:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Ransho revision","contactName":"Sahib Singh","contactTitle":"Co-Founder","contactEmail":"sahib.singh@ranchochemistry.com","contactNumber":"8872778166","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2028","meetingId":"MTG-2028","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-28","meetingTime":"03:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Sage By Mala","contactName":"Tushar Miglani","contactTitle":"Co-Founder","contactEmail":"tushar@sagebymala.com","contactNumber":"8851201286","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2029","meetingId":"MTG-2029","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-28","meetingTime":"03:30 PM","meetingStatus":"done","meetingLink":"","companyName":"Fix My Curls","contactName":"Jayant Shah","contactTitle":"Head Of Business","contactEmail":"jayant@fixmycurls.com","contactNumber":"9411303207","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2030","meetingId":"MTG-2030","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-29","meetingTime":"01:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Asian Footwears Pvt Ltd","contactName":"RB Sharma","contactTitle":"Business Head- MT & ISD","contactEmail":"rbsharma@asianfootwears.com","contactNumber":"9911228742","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2031","meetingId":"MTG-2031","month":"January","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-01-29","meetingTime":"11:00 AM","meetingStatus":"done","meetingLink":"","companyName":"Maruti Suzuki       India Limited","contactName":"Uditha Singh","contactTitle":"Head Marketing Analytics and CRM","contactEmail":"uditha.singh@maruti.co.in","contactNumber":"7575003910","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2032","meetingId":"MTG-2032","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-02","meetingTime":"12:30 PM","meetingStatus":"done","meetingLink":"","companyName":"DBS Bank","contactName":"Shariq Shaikh","contactTitle":"Performance Marketing & Martech","contactEmail":"shariqshaikh@dbs.com","contactNumber":"9372700972","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2033","meetingId":"MTG-2033","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-04","meetingTime":"01:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Womancart","contactName":"Prateek Batra","contactTitle":"Head – Marketing & Business Growth","contactEmail":"prateek@womancart.in","contactNumber":"9755928377","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2034","meetingId":"MTG-2034","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-05","meetingTime":"12:30 PM","meetingStatus":"done","meetingLink":"","companyName":"Neuberg Diagnostics","contactName":"Vijay Ankush Pashte","contactTitle":"AVP and Head of Digital Marketing","contactEmail":"vijay.pashte@neubergdiagnostics.com","contactNumber":"9022784381","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2035","meetingId":"MTG-2035","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-06","meetingTime":"03:00 PM","meetingStatus":"done","meetingLink":"","companyName":"LOUIS STITCH","contactName":"Akshat Jangotra","contactTitle":"Marketing Head","contactEmail":"akshat.jangotra@louisstitch.com","contactNumber":"8447397597","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2036","meetingId":"MTG-2036","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-09","meetingTime":"02:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Avishkaar","contactName":"Dhruv Sharma","contactTitle":"E-commerce & Marketing Team Lead","contactEmail":"dhruv.sharma@avishkaar.cc","contactNumber":"8800101124","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2037","meetingId":"MTG-2037","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-09","meetingTime":"04:30 PM","meetingStatus":"done","meetingLink":"","companyName":"Simplotel","contactName":"Shuvam Das","contactTitle":"Product Manager","contactEmail":"shuvam@simplotel.com","contactNumber":"8699838447","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2038","meetingId":"MTG-2038","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-10","meetingTime":"02:30 PM","meetingStatus":"done","meetingLink":"","companyName":"CoFynd","contactName":"Ashok Kumar","contactTitle":"Senior SEO Analyst","contactEmail":"ashok@cofynd.com","contactNumber":"9016929117","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2039","meetingId":"MTG-2039","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-10","meetingTime":"03:00 PM","meetingStatus":"done","meetingLink":"","companyName":"VEIRDO","contactName":"Dhaval Ahir","contactTitle":"Co-Founder","contactEmail":"dhaval@awesomefab.in","contactNumber":"7015263003","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2040","meetingId":"MTG-2040","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-11","meetingTime":"02:30 PM","meetingStatus":"done","meetingLink":"","companyName":"Novatr","contactName":"Harkunwar Singh","contactTitle":"CEO","contactEmail":"harkunwar@novatr.com","contactNumber":"9017181818","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2041","meetingId":"MTG-2041","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-11","meetingTime":"11:30 AM","meetingStatus":"done","meetingLink":"","companyName":"Vummidi Bangaru Jewellers","contactName":"Deepansh Bhargava","contactTitle":"Vice President","contactEmail":"deepansh@vummidi.com","contactNumber":"9343897011","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2042","meetingId":"MTG-2042","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-11","meetingTime":"12:30 PM","meetingStatus":"done","meetingLink":"","companyName":"Phodu Club","contactName":"Dhruva Angle","contactTitle":"Co-Founder","contactEmail":"http://dhruva@phodu.club/","contactNumber":"8459073409","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2043","meetingId":"MTG-2043","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-16","meetingTime":"01:30 PM","meetingStatus":"done","meetingLink":"","companyName":"Toolsvilla.com","contactName":"Chetan Khaitan","contactTitle":"Founder & CEO","contactEmail":"chetan@toolsvilla.com","contactNumber":"8116204055","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2044","meetingId":"MTG-2044","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-18","meetingTime":"02:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Acko","contactName":"Vipin Nair","contactTitle":"Vice President, Brand","contactEmail":"vipin.nair@acko.com","contactNumber":"9686512738","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2045","meetingId":"MTG-2045","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-19","meetingTime":"01:30 PM","meetingStatus":"done","meetingLink":"","companyName":"The House of Rare","contactName":"Pulkit Verma","contactTitle":"Ecom Head","contactEmail":"pulkit@thehouseofrare.com","contactNumber":"8447451930","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2046","meetingId":"MTG-2046","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-20","meetingTime":"12:00 PM","meetingStatus":"done","meetingLink":"","companyName":"P N Gadgil And Sons Ltd","contactName":"Rahul Patil","contactTitle":"Sales Head","contactEmail":"rahul.patil@pngsl.com","contactNumber":"8956746914","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2047","meetingId":"MTG-2047","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-20","meetingTime":"04:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Alive","contactName":"vivek","contactTitle":"Founder","contactEmail":"vivek@iamalive.app","contactNumber":"9731735544","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2048","meetingId":"MTG-2048","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-23","meetingTime":"11:00 AM","meetingStatus":"done","meetingLink":"","companyName":"Knowledge Gate","contactName":"Rupashi Jain","contactTitle":"COO & CFO","contactEmail":"rupashi@knowledgegate.in","contactNumber":"8800540705","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2049","meetingId":"MTG-2049","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-23","meetingTime":"12:45 PM","meetingStatus":"done","meetingLink":"","companyName":"Naaptol Online Shopping Pvt. Ltd","contactName":"Vice President-Operations","contactTitle":"Suresh Dubey","contactEmail":"suresh.dubey@naaptol.com","contactNumber":"9810828938","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2050","meetingId":"MTG-2050","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-24","meetingTime":"02:30 PM","meetingStatus":"done","meetingLink":"","companyName":"ScaleSauce","contactName":"Dhruven Turakhia","contactTitle":"Digital Performance Marketing","contactEmail":"perform.2@scalesauce.co","contactNumber":"7977802078","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2051","meetingId":"MTG-2051","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-25","meetingTime":"04:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Banana Club","contactName":"Senior Digital Marketing Specialist","contactTitle":"Lakshmi Charan","contactEmail":"ads@bananaclub.co.in","contactNumber":"9740377393","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2052","meetingId":"MTG-2052","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-26","meetingTime":"11:00 AM","meetingStatus":"done","meetingLink":"","companyName":"Columbia Sportswear","contactName":"Program Manager","contactTitle":"Manas Jaiswal","contactEmail":"manas.jaiswal@chogori       india.com","contactNumber":"9794939232","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2053","meetingId":"MTG-2053","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-26","meetingTime":"01:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Spyne","contactName":"Product Head","contactTitle":"Amit Walia","contactEmail":"amit@spyne.ai","contactNumber":"","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2054","meetingId":"MTG-2054","month":"February","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-02-27","meetingTime":"01:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Kaff        India","contactName":"Head of Marketing","contactTitle":"Rupali Singh","contactEmail":"rupali.singh@kaff.in","contactNumber":"9953772281","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2055","meetingId":"MTG-2055","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-02","meetingTime":"04:00 PM","meetingStatus":"done","meetingLink":"","companyName":"1 Finance","contactName":"Senior Manager","contactTitle":"Aniket Mohite","contactEmail":"aniket.mohite@1finance.co.in","contactNumber":"9326864768","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2056","meetingId":"MTG-2056","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-03","meetingTime":"11:00 AM","meetingStatus":"done","meetingLink":"","companyName":"Dressfolk","contactName":"Senior Manager Ecommerce","contactTitle":"Apar Singh","contactEmail":"apar.s@dressfolk.com","contactNumber":"8860014420","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2057","meetingId":"MTG-2057","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-05","meetingTime":"11:00 AM","meetingStatus":"done","meetingLink":"","companyName":"Antinorm","contactName":"Finance and Growth Head","contactTitle":"Shivangi Sardana","contactEmail":"shivangi@antinorm.co","contactNumber":"9818227922","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2058","meetingId":"MTG-2058","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-10","meetingTime":"12:00 PM","meetingStatus":"done","meetingLink":"","companyName":"UNIVO Education","contactName":"Chief Executive Officer","contactTitle":"Siddharth Banerjee","contactEmail":"sbanerjee@univoedtech.com","contactNumber":"9619218989","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2059","meetingId":"MTG-2059","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-10","meetingTime":"12:30 PM","meetingStatus":"done","meetingLink":"","companyName":"Capri Global Capital","contactName":"Product Manager","contactTitle":"Lakhshya Khurana","contactEmail":"lakhshya.khurana@capriglobal.in","contactNumber":"8826373942","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2060","meetingId":"MTG-2060","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-10","meetingTime":"03:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Equentis","contactName":"Senior General Manager","contactTitle":"Aatish Shah","contactEmail":"aatish.shah@equentis.com","contactNumber":"9870796006","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2061","meetingId":"MTG-2061","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-10","meetingTime":"01:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Explurger","contactName":"Vice President Marketing","contactTitle":"Kush Bhardwaj","contactEmail":"kush.bhardwaj@explurger.com","contactNumber":"9999071802","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2062","meetingId":"MTG-2062","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-10","meetingTime":"03:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Freshcon        India","contactName":"Marketing Manager","contactTitle":"Dimpy Gupta","contactEmail":"dimpy.gupta@freshcon        india.com","contactNumber":"9930080890","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2063","meetingId":"MTG-2063","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-14","meetingTime":"03:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Prudent Corporate Advisory Services","contactName":"Head, Performance Marketing","contactTitle":"Poonam Moridhara","contactEmail":"poonam.m@prudentcorporate.com","contactNumber":"7622098574","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2064","meetingId":"MTG-2064","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-16","meetingTime":"12:30 PM","meetingStatus":"done","meetingLink":"","companyName":"TechnoSport","contactName":"Head - Brand Marketing and Communication","contactTitle":"Patralika Agrawal","contactEmail":"patralika.agrawal@technosport.in","contactNumber":"9900780239","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2065","meetingId":"MTG-2065","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-17","meetingTime":"01:00 PM","meetingStatus":"done","meetingLink":"","companyName":"So Fetch Shop","contactName":"Cofounder","contactTitle":"Abhimanyu Malik","contactEmail":"abhimanyu@sofetchshop.com","contactNumber":"","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2066","meetingId":"MTG-2066","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-23","meetingTime":"01:00 PM","meetingStatus":"done","meetingLink":"","companyName":"ANNY","contactName":"Chief Growth Officer","contactTitle":"Ritika Goel","contactEmail":"ritika.goel@styleanny.in","contactNumber":"8968574997","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2067","meetingId":"MTG-2067","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-24","meetingTime":"11:30 AM","meetingStatus":"done","meetingLink":"","companyName":"Vehicleinfo","contactName":"Chief Executive Officer","contactTitle":"Chirag Pipaliya","contactEmail":"chirag@vehicleinfo.app","contactNumber":"9033993750","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2068","meetingId":"MTG-2068","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-24","meetingTime":"05:30 PM","meetingStatus":"done","meetingLink":"","companyName":"Femmella","contactName":"Director","contactTitle":"Kavya Arora","contactEmail":"kavya@femella.in","contactNumber":"9810030972","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2069","meetingId":"MTG-2069","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-25","meetingTime":"12:30 PM","meetingStatus":"done","meetingLink":"","companyName":"Edme Insurance Brokers","contactName":"Senior Marketing Manager","contactTitle":"Shilpa Saini","contactEmail":"shilpa.saini@edmeinsurance.com","contactNumber":"7296819089","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2070","meetingId":"MTG-2070","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-25","meetingTime":"02:30 PM","meetingStatus":"done","meetingLink":"","companyName":"CashRich","contactName":"Head, Product Management","contactTitle":"Ashwin Ks","contactEmail":"ashwin@cashrich.com","contactNumber":"9892856478","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2071","meetingId":"MTG-2071","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-26","meetingTime":"04:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Brand Concepts Limited","contactName":"Digital Marketing Specialist","contactTitle":"Kuldeep Thakur","contactEmail":"kuldeep.thakur@brandconcepts.in","contactNumber":"9993330505","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2072","meetingId":"MTG-2072","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-30","meetingTime":"01:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Overlays Clothing Pvt Ltd","contactName":"Marketing Manager & Executive Assistant","contactTitle":"Mahee Jain","contactEmail":"mahee@overlaysclothing.com","contactNumber":"","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2073","meetingId":"MTG-2073","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-31","meetingTime":"12:30 PM","meetingStatus":"done","meetingLink":"","companyName":"M2M Ferries","contactName":"Director","contactTitle":"Devika Saigal","contactEmail":"devika@m2mferries.com","contactNumber":"9967976969","remarks":"","additionalInfo":"","meetingSummary":""},
    {"id":"d2074","meetingId":"MTG-2074","month":"March","year":2026,"clientName":"CleverTap- In","geo":"India","salesRep":"","accountManager":"Manshi","meetingDate":"2026-03-31","meetingTime":"03:00 PM","meetingStatus":"done","meetingLink":"","companyName":"Vasundhara Infotech","contactName":"Chief Marketing Officer","contactTitle":"Somish Kakadiya","contactEmail":"somish@vasundhara.io","contactNumber":"9409017007","remarks":"","additionalInfo":"","meetingSummary":""},
  ],
  p3: [
    { id: "d7", meetingId: "MTG-1007", month: "April", year: 2026, clientName: "BlueDove", geo: "US-West", salesRep: "Derek Miles", accountManager: "Akash S", meetingDate: "2026-04-01", meetingTime: "11:00 AM", meetingStatus: "done", meetingLink: "https://meet.google.com/01g3p5g3", companyName: "BlueDove", contactName: "Sarah Chen", contactTitle: "COO", contactEmail: "sarah.c@bluedove.io", contactNumber: "+1-650-555-0301", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d8", meetingId: "MTG-1008", month: "April", year: 2026, clientName: "BlueDove", geo: "EU", salesRep: "Derek Miles", accountManager: "Rohit M", meetingDate: "2026-04-07", meetingTime: "01:00 PM", meetingStatus: "scheduled", meetingLink: "https://meet.google.com/e4jb8nsq", companyName: "BlueDove", contactName: "Hans Mueller", contactTitle: "CTO", contactEmail: "hans.m@bluedove.io", contactNumber: "+49-89-555-0302", remarks: "", additionalInfo: "", meetingSummary: "" },
  ],
  p4: [
    { id: "d9", meetingId: "MTG-1009", month: "April", year: 2026, clientName: "Evality", geo: "APAC", salesRep: "Tanya Rao", accountManager: "Prateek G", meetingDate: "2026-04-04", meetingTime: "10:00 AM", meetingStatus: "done", meetingLink: "https://meet.google.com/20wwabjl", companyName: "Evality", contactName: "Vikram Desai", contactTitle: "Founder", contactEmail: "vikram.d@evality.com", contactNumber: "+91-80-555-0401", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d10", meetingId: "MTG-1010", month: "March", year: 2026, clientName: "Evality", geo: "APAC", salesRep: "Tanya Rao", accountManager: "Simran K", meetingDate: "2026-03-22", meetingTime: "04:00 PM", meetingStatus: "done", meetingLink: "https://meet.google.com/wtltozki", companyName: "Evality", contactName: "Meera Shetty", contactTitle: "VP Product", contactEmail: "meera.s@evality.com", contactNumber: "+91-80-555-0402", remarks: "", additionalInfo: "", meetingSummary: "" },
  ],
  p5: [
    { id: "d11", meetingId: "MTG-1011", month: "April", year: 2026, clientName: "Onecap", geo: "APAC", salesRep: "Arjun Patel", accountManager: "Deepak R", meetingDate: "2026-04-05", meetingTime: "11:30 AM", meetingStatus: "scheduled", meetingLink: "https://meet.google.com/7ridvnjw", companyName: "Onecap", contactName: "Rohan Gupta", contactTitle: "CEO", contactEmail: "rohan.g@onecap.in", contactNumber: "+91-22-555-0501", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d12", meetingId: "MTG-1012", month: "April", year: 2026, clientName: "Onecap", geo: "US-West", salesRep: "Arjun Patel", accountManager: "Ankita T", meetingDate: "2026-04-14", meetingTime: "09:00 AM", meetingStatus: "scheduled", meetingLink: "https://meet.google.com/grxfzis2", companyName: "Onecap", contactName: "Divya Nair", contactTitle: "CTO", contactEmail: "divya.n@onecap.in", contactNumber: "+91-22-555-0502", remarks: "", additionalInfo: "", meetingSummary: "" },
  ],
  p6: [
    { id: "d13", meetingId: "MTG-1013", month: "April", year: 2026, clientName: "Mynd", geo: "APAC", salesRep: "Sneha Iyer", accountManager: "Akash S", meetingDate: "2026-04-02", meetingTime: "10:00 AM", meetingStatus: "scheduled", meetingLink: "https://meet.google.com/h7rhyn0g", companyName: "Mynd", contactName: "Karan Malhotra", contactTitle: "Founder", contactEmail: "karan.m@mynd.co", contactNumber: "+91-11-555-0601", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d14", meetingId: "MTG-1014", month: "March", year: 2026, clientName: "Mynd", geo: "EU", salesRep: "Sneha Iyer", accountManager: "Rohit M", meetingDate: "2026-03-25", meetingTime: "04:30 PM", meetingStatus: "scheduled", meetingLink: "https://meet.google.com/8ofaxofj", companyName: "Mynd", contactName: "Lisa Thompson", contactTitle: "Head of Growth", contactEmail: "lisa.t@mynd.co", contactNumber: "+44-20-555-0602", remarks: "", additionalInfo: "", meetingSummary: "" },
  ],
  p7: [
    { id: "d1", meetingId: "MTG-001", month: "January", year: 2026, clientName: "Actyv", geo: "India", salesRep: "Krishna", accountManager: "", meetingDate: "2026-01-30", meetingTime: "04:00 PM", meetingStatus: "done", meetingLink: "", companyName: "Calibehr Business Support Services Pvt. Ltd.", contactName: "Shadab Shaikh", contactTitle: "DGM- Technology", contactEmail: "shadab.s@calibehr.com", contactNumber: "9819414708", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d2", meetingId: "MTG-002", month: "February", year: 2026, clientName: "Actyv", geo: "India", salesRep: "Krishna", accountManager: "", meetingDate: "2026-02-02", meetingTime: "03:00 PM", meetingStatus: "done", meetingLink: "", companyName: "Anand Rathi Wealth Limited", contactName: "Nikhil Anand", contactTitle: "Manager- Digital Transformation & Adoption", contactEmail: "nikhilanand@rathi.com", contactNumber: "", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d3", meetingId: "MTG-003", month: "February", year: 2026, clientName: "Actyv", geo: "India", salesRep: "Krishna", accountManager: "", meetingDate: "2026-02-10", meetingTime: "03:00 PM", meetingStatus: "done", meetingLink: "", companyName: "ITTI Pvt Ltd", contactName: "Harsha Narayanappa", contactTitle: "Chief Operating Officer", contactEmail: "harsha.bn@itti.com", contactNumber: "", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d4", meetingId: "MTG-004", month: "February", year: 2026, clientName: "Actyv", geo: "India", salesRep: "Krishna", accountManager: "", meetingDate: "2026-02-13", meetingTime: "02:00 PM", meetingStatus: "done", meetingLink: "", companyName: "UDS Group", contactName: "Samuel Cristopher", contactTitle: "VP Digital Transformation", contactEmail: "samuel.c@uds.in", contactNumber: "", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d5", meetingId: "MTG-005", month: "February", year: 2026, clientName: "Actyv", geo: "India", salesRep: "Krishna", accountManager: "", meetingDate: "2026-02-18", meetingTime: "04:00 PM", meetingStatus: "done", meetingLink: "", companyName: "Mintifi", contactName: "Hemant Bora", contactTitle: "AVP Strategy and Digital Transformation", contactEmail: "hemant.bora@mintifi.com", contactNumber: "", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d6", meetingId: "MTG-006", month: "February", year: 2026, clientName: "Actyv", geo: "India", salesRep: "Krishna", accountManager: "", meetingDate: "2026-02-25", meetingTime: "02:30 PM", meetingStatus: "done", meetingLink: "", companyName: "Marwadi Shares and Finance Ltd.", contactName: "Gaurav Kalamkar", contactTitle: "Chief Manager - Digital Strategy", contactEmail: "gaurav.kalamkar@marwadigroup.in", contactNumber: "", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d7", meetingId: "MTG-007", month: "March", year: 2026, clientName: "Actyv", geo: "India", salesRep: "Krishna", accountManager: "", meetingDate: "2026-03-19", meetingTime: "04:00 PM", meetingStatus: "done", meetingLink: "", companyName: "Kreditbee", contactName: "Deepam Mundhra", contactTitle: "Assistant Program Manager", contactEmail: "deepam.mundhra@kreditbee.in", contactNumber: "", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d8", meetingId: "MTG-008", month: "March", year: 2026, clientName: "Actyv", geo: "India", salesRep: "Krishna", accountManager: "", meetingDate: "2026-03-24", meetingTime: "03:00 PM", meetingStatus: "done", meetingLink: "", companyName: "Wissen Infotech", contactName: "Jagadish Gokavarapu", contactTitle: "VP Technology", contactEmail: "jagadish.gokavarapu@wisseninfotech.com", contactNumber: "", remarks: "", additionalInfo: "", meetingSummary: "" },
  ],
  p8: [
    { id: "d18", meetingId: "MTG-1018", month: "April", year: 2026, clientName: "Zigtal", geo: "US-West", salesRep: "Marcus Flynn", accountManager: "Ankita T", meetingDate: "2026-04-03", meetingTime: "11:00 AM", meetingStatus: "scheduled", meetingLink: "https://meet.google.com/jfepv974", companyName: "Zigtal", contactName: "David Chen", contactTitle: "CEO", contactEmail: "david.c@zigtal.com", contactNumber: "+1-415-555-0801", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d19", meetingId: "MTG-1019", month: "March", year: 2026, clientName: "Zigtal", geo: "APAC", salesRep: "Marcus Flynn", accountManager: "Akash S", meetingDate: "2026-03-18", meetingTime: "10:30 AM", meetingStatus: "done", meetingLink: "https://meet.google.com/h3a5nx3y", companyName: "Zigtal", contactName: "Nisha Patel", contactTitle: "COO", contactEmail: "nisha.p@zigtal.com", contactNumber: "+91-80-555-0802", remarks: "", additionalInfo: "", meetingSummary: "" },
  ],
  p9: [
    { id: "d20", meetingId: "MTG-1020", month: "April", year: 2026, clientName: "VWO", geo: "APAC", salesRep: "Linda Carter", accountManager: "Rohit M", meetingDate: "2026-04-07", meetingTime: "11:00 AM", meetingStatus: "done", meetingLink: "https://meet.google.com/3lbqe8ax", companyName: "VWO", contactName: "Paras Chopra", contactTitle: "Founder", contactEmail: "paras.c@vwo.com", contactNumber: "+91-11-555-0901", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d21", meetingId: "MTG-1021", month: "April", year: 2026, clientName: "VWO", geo: "US-East", salesRep: "Linda Carter", accountManager: "Prateek G", meetingDate: "2026-04-15", meetingTime: "03:00 PM", meetingStatus: "scheduled", meetingLink: "https://meet.google.com/xlw9bvxy", companyName: "VWO", contactName: "Sparsh Gupta", contactTitle: "COO", contactEmail: "sparsh.g@vwo.com", contactNumber: "+91-11-555-0902", remarks: "", additionalInfo: "", meetingSummary: "" },
  ],
  p10: [
    { id: "d22", meetingId: "MTG-1022", month: "April", year: 2026, clientName: "Pazo", geo: "APAC", salesRep: "Rachel Kim", accountManager: "Simran K", meetingDate: "2026-04-01", meetingTime: "09:30 AM", meetingStatus: "done", meetingLink: "https://meet.google.com/ckrvasvo", companyName: "Pazo", contactName: "Neeraj Joshi", contactTitle: "CEO", contactEmail: "neeraj.j@pazo.app", contactNumber: "+91-80-555-1001", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d23", meetingId: "MTG-1023", month: "March", year: 2026, clientName: "Pazo", geo: "US-West", salesRep: "Rachel Kim", accountManager: "Deepak R", meetingDate: "2026-03-21", meetingTime: "01:30 PM", meetingStatus: "done", meetingLink: "https://meet.google.com/y2fdphzq", companyName: "Pazo", contactName: "Aditi Rao", contactTitle: "VP Product", contactEmail: "aditi.r@pazo.app", contactNumber: "+91-80-555-1002", remarks: "", additionalInfo: "", meetingSummary: "" },
  ],
  p11: [
    { id: "d24", meetingId: "MTG-1024", month: "April", year: 2026, clientName: "Venwiz", geo: "APAC", salesRep: "Sandra Wells", accountManager: "Ankita T", meetingDate: "2026-04-04", meetingTime: "10:00 AM", meetingStatus: "done", meetingLink: "https://meet.google.com/h0kfoajw", companyName: "Venwiz", contactName: "Ashwin Kumar", contactTitle: "Co-founder", contactEmail: "ashwin.k@venwiz.com", contactNumber: "+91-44-555-1101", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d25", meetingId: "MTG-1025", month: "April", year: 2026, clientName: "Venwiz", geo: "EU", salesRep: "Sandra Wells", accountManager: "Akash S", meetingDate: "2026-04-12", meetingTime: "02:30 PM", meetingStatus: "scheduled", meetingLink: "https://meet.google.com/g1m1xszu", companyName: "Venwiz", contactName: "Indraneel Gupta", contactTitle: "CTO", contactEmail: "indraneel.g@venwiz.com", contactNumber: "+91-44-555-1102", remarks: "", additionalInfo: "", meetingSummary: "" },
  ],
  p12: [
    { id: "d26", meetingId: "MTG-1026", month: "April", year: 2026, clientName: "InFeedo", geo: "APAC", salesRep: "Vikram Desai", accountManager: "Rohit M", meetingDate: "2026-04-05", meetingTime: "11:30 AM", meetingStatus: "scheduled", meetingLink: "https://meet.google.com/n7gm0fx0", companyName: "InFeedo", contactName: "Tanmaya Jain", contactTitle: "CEO", contactEmail: "tanmaya.j@infeedo.ai", contactNumber: "+91-11-555-1201", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d27", meetingId: "MTG-1027", month: "April", year: 2026, clientName: "InFeedo", geo: "US-East", salesRep: "Vikram Desai", accountManager: "Prateek G", meetingDate: "2026-04-16", meetingTime: "02:00 PM", meetingStatus: "done", meetingLink: "https://meet.google.com/qd3xuor5", companyName: "InFeedo", contactName: "Varun Puri", contactTitle: "CTO", contactEmail: "varun.p@infeedo.ai", contactNumber: "+1-646-555-1202", remarks: "", additionalInfo: "", meetingSummary: "" },
    { id: "d28", meetingId: "MTG-1028", month: "March", year: 2026, clientName: "InFeedo", geo: "EU", salesRep: "Vikram Desai", accountManager: "Simran K", meetingDate: "2026-03-23", meetingTime: "03:30 PM", meetingStatus: "done", meetingLink: "https://meet.google.com/xx6t5qus", companyName: "InFeedo", contactName: "Anisha Sharma", contactTitle: "VP People", contactEmail: "anisha.s@infeedo.ai", contactNumber: "+44-20-555-1203", remarks: "", additionalInfo: "", meetingSummary: "" },
  ],
};
