import type { LeadResearch, PhaseState, ScoredAccount, Stakeholder } from "../types";

export interface PromptBuildInput {
  rows: {
    account: ScoredAccount;
    stakeholder: Stakeholder;
    research: LeadResearch;
    email: string;
    emailStatus: string;
  }[];
  sellerName: string;
}

export interface CompiledPrompt {
  domain: string;
  personKey: string;
  fullName: string;
  prompt: string;
}

export interface PromptBuildOutput {
  prompts: CompiledPrompt[];
}

function joinList(items: string[] | undefined, sep = ", "): string {
  if (!items || items.length === 0) return "(none provided)";
  return items.join(sep);
}

export function buildLeadPrompt(args: {
  sellerName: string;
  account: ScoredAccount;
  stakeholder: Stakeholder;
  research: LeadResearch;
  email: string;
  emailStatus: string;
}): string {
  const { sellerName, account, stakeholder, research } = args;

  const lines: string[] = [];
  lines.push(`Write a 3-step cold email sequence for the lead below, following the SKILL.md style I've configured in this Claude project's instructions. The Client Brief (also in project instructions) tells you what ${sellerName} sells, who they target, and what pains they solve — use it as your map.`);
  lines.push("");
  lines.push("This brief is RICH and SPECIFIC — every field below was generated by an upstream research + personalization agent that combined the prospect's own product/page signals with this individual's LinkedIn activity. Treat it as ground truth. Do NOT invent additional facts. Do NOT ignore fields. The emails should read like they were written FOR this person, not a generic role.");
  lines.push("");
  lines.push("LEAD (the human you're writing to)");
  lines.push(`- First name: ${stakeholder.firstName || "(unknown)"}`);
  lines.push(`- Last name: ${stakeholder.lastName || ""}`);
  lines.push(`- Full name: ${stakeholder.fullName || ""}`);
  lines.push(`- Title: ${stakeholder.title || "(unknown)"}`);
  lines.push(`- ICP role bucket (use to shape tone + jargon): ${research.icpRole || "(generic)"}`);
  lines.push(`- Email: ${args.email || "(no verified email)"}${args.emailStatus ? ` [${args.emailStatus}]` : ""}`);
  lines.push(`- LinkedIn: ${stakeholder.linkedinUrl || "(none)"}`);
  if (research.personEvidence && research.personEvidence.length > 0) {
    lines.push(`- LinkedIn signals on THIS person (drives subject 2 + body 2 personalization):`);
    for (const e of research.personEvidence) lines.push(`    • ${e}`);
  }
  if (research.socialAngle) lines.push(`- Social angle (one citable thread to their LinkedIn — body 2 should weave this in naturally): ${research.socialAngle}`);
  lines.push("");
  lines.push("ACCOUNT (the company)");
  lines.push(`- Company: ${account.name}`);
  lines.push(`- Domain: ${account.domain}`);
  lines.push(`- Industry: ${account.industry || "(unknown)"}`);
  lines.push(`- Employees: ${account.estimatedNumEmployees || "(unknown)"}`);
  lines.push(`- Country: ${account.country || "(unknown)"}`);
  lines.push(`- Founded: ${account.foundedYear || "(unknown)"}`);
  if (account.shortDescription) lines.push(`- Apollo description: ${account.shortDescription}`);
  if (account.linkedinUrl) lines.push(`- Company LinkedIn: ${account.linkedinUrl}`);
  lines.push(`- Lead score: ${account.score} (${account.segment})`);
  lines.push("");
  lines.push("BUYING THESIS (why they're buyable now — read this first, then write to it)");
  if (research.buyingHypothesis) lines.push(`- Buying hypothesis: ${research.buyingHypothesis}`);
  if (research.shouldEmail) lines.push(`- Decision: should-email = ${research.shouldEmail}${research.confidenceLevel ? ` (confidence: ${research.confidenceLevel})` : ""}${research.shouldEmailReason ? ` — ${research.shouldEmailReason}` : ""}`);
  if (typeof research.buyerSignalScore === "number" && research.buyerSignalScore > 0) lines.push(`- Buyer signal score: ${research.buyerSignalScore}/100`);
  if (research.evidenceList && research.evidenceList.length > 0) {
    lines.push(`- Evidence (account + person signals you can lean on — use 1-2 in body 1, do NOT cite all):`);
    for (const e of research.evidenceList) lines.push(`    • ${e}`);
  }
  lines.push("");
  lines.push("PROSPECT TRUTH (use only what's here, do NOT invent)");
  lines.push(`- What they sell: ${research.whatTheySell || "(no detail — paraphrase from the description above)"}`);
  lines.push(`- Their customers: ${research.theirCustomers || "(unknown — infer reasonably from segment + size)"}`);
  lines.push(`- Their stage: ${research.theirStage || "unknown"}`);
  lines.push("");
  lines.push("ANGLES (the ICP-shaded framing — already tailored to this person's role)");
  lines.push(`- Top pain (THEIR specific pain — the one this ICP role actually feels): ${research.topPain || "(use a pain from the Client Brief that fits this segment)"}`);
  lines.push(`- Value angle (how ${sellerName} solves THAT pain in THIS persona's language): ${research.valueAngle || "(pick a capability from the Client Brief that maps to the top pain)"}`);
  lines.push(`- Body 1 opener observation (concrete page/funnel/UX detail on THEIR product): ${research.observationAngle || "(generate one from their site)"}`);
  if (research.secondaryObservation) lines.push(`- Body 2 observation (DIFFERENT page or step from body 1): ${research.secondaryObservation}`);
  if (research.signalForBody3) lines.push(`- Body 3 breakup hook (challenge they'll face soon): ${research.signalForBody3}`);
  lines.push(`- Subject 1 topic: ${research.subjectTopic || "Improving Conversions"}`);
  lines.push(`- Social proof for body 1 paragraph 2 (cite all three, in this order): ${joinList(research.socialProofMatch)}`);
  lines.push("");
  lines.push("OUTPUT FORMAT");
  lines.push("Return ONLY this JSON, no preamble, no explanation:");
  lines.push("{");
  lines.push(`  "subject_1": "${stakeholder.firstName || "{first_name}"}, <subject_topic from above>",`);
  lines.push(`  "body_1": "...",`);
  lines.push(`  "subject_2": "${stakeholder.firstName || "{first_name}"}, <different topic — pull from social angle / person evidence if available>",`);
  lines.push(`  "body_2": "...",`);
  lines.push(`  "subject_3": "${stakeholder.firstName || "{first_name}"}, <breakup topic>",`);
  lines.push(`  "body_3": "..."`);
  lines.push("}");
  lines.push("");
  lines.push("RULES (from SKILL in project instructions)");
  lines.push("- Body 1: 90-130 words, 3 paragraphs, must open \"I was checking out " + (account.name || "{company}") + "'s website and noticed...\" then bridge to the OPENER OBSERVATION above, then to TOP PAIN.");
  lines.push("- Body 1 paragraph 2 must say \"That's exactly what " + sellerName + " helps with\" and stack the three social-proof brands listed above (in that order).");
  lines.push("- Body 1 must include the reassurance line (\"Often, these don't require a full redesign. Even small, validated changes can create measurable improvements.\") and the ease coda (\"without heavy dev effort\").");
  lines.push("- Body 1 paragraph 3: a 15-25 word CTA naming \"" + (account.name || "{company}") + "\" and \"20 min\".");
  lines.push("- Body 2: 70-110 words, 2-3 paragraphs. MUST weave in the SOCIAL ANGLE / PERSON EVIDENCE if present (1 line, conversational, NOT a stalker-vibe). Then DIFFERENT capability + DIFFERENT observation from body 1.");
  lines.push("- Body 3: 50-90 words, 2 paragraphs, breakup tone, no new pitch. If a body-3 breakup hook is provided above, anchor on it.");
  lines.push("- Subjects: 4-6 words, title-case, format \"" + (stakeholder.firstName || "{First Name}") + ", <Topic>\". 3 subjects must differ in topic.");
  lines.push("- BANNED openers: \"Saw your Series C\", \"Congrats on your raise\", \"Read about your acquisition\", \"Hope this finds you well\".");
  lines.push("- No greetings, no sign-offs in any body. No em dashes. No spintax. No template variables.");

  return lines.join("\n");
}

export function promptBuildAgent(input: PromptBuildInput): { output: PromptBuildOutput; state: Pick<PhaseState, "log" | "metrics" | "inputCount" | "outputCount"> } {
  const prompts: CompiledPrompt[] = [];
  for (const row of input.rows) {
    const prompt = buildLeadPrompt({
      sellerName: input.sellerName,
      account: row.account,
      stakeholder: row.stakeholder,
      research: row.research,
      email: row.email,
      emailStatus: row.emailStatus,
    });
    prompts.push({ domain: row.account.domain, personKey: row.stakeholder.personKey || "", fullName: row.stakeholder.fullName, prompt });
  }
  const avgChars = prompts.length === 0 ? 0 : Math.round(prompts.reduce((a, p) => a + p.prompt.length, 0) / prompts.length);
  return {
    output: { prompts },
    state: {
      log: [
        `Built ${prompts.length} per-lead Claude prompts (paste-and-go).`,
        `Average prompt length: ${avgChars} chars.`,
        `Workflow: paste each prompt into a Claude Project that has SKILL.md + Client Brief as project instructions.`,
      ],
      metrics: { prompts: prompts.length, avgPromptChars: avgChars, mode: "claude-paste" },
      inputCount: input.rows.length,
      outputCount: prompts.length,
    },
  };
}
